# Generated by Django 5.1.3 on 2024-11-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donation_type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('date_of_donation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='orphan',
            name='available_for_adoption',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
