# Generated by Django 5.1.3 on 2024-11-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0004_alter_donation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_type',
        ),
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
