# Generated by Django 5.1.3 on 2024-11-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0005_remove_donation_donation_type_donation_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='created_at',
            new_name='donation_date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
        migrations.AddField(
            model_name='donation',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('money', 'Money'), ('clothes', 'Clothes'), ('toys', 'Toys'), ('school_supplies', 'School Supplies'), ('food', 'Food Items'), ('blankets', 'Blankets')], default='2024-11-16', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(max_length=100),
        ),
    ]
